# Generated by Django 5.1.4 on 2025-01-31 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentmail', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Motorcycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=255)),
                ('model_name', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('category', models.CharField(max_length=255)),
            ],
        ),
    ]
